# Generated by Django 5.1.3 on 2024-12-14 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_blogpost_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='is_liked',
            field=models.BooleanField(default=False),
        ),
    ]
