# Generated by Django 5.1.3 on 2024-12-17 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_profile_is_followed_alter_blogpost_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/badges/')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='badge', to='main.profile')),
            ],
        ),
    ]
