# Generated by Django 5.1.3 on 2024-12-17 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_badge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badge',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='badge', to='main.profile'),
        ),
    ]
