# Generated by Django 5.1.3 on 2024-12-17 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_badge_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='badge',
            old_name='profile',
            new_name='user',
        ),
    ]
