# Generated by Django 5.1.3 on 2024-12-17 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_remove_badge_user_badge_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badge',
            name='profile',
            field=models.ManyToManyField(blank=True, null=True, related_name='badges', to='main.profile'),
        ),
    ]
